# Generated by Django 3.2.16 on 2023-12-17 13:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_alter_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Введите сообщение', max_length=500, verbose_name='Сообщение'),
        ),
    ]
